id: I54A1A24C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:35:39+00:00'
last_modified: '2022-06-08T05:44:58.527492+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22505
  title: ཕྱག་ཆེན་ཁྲིད་ཡིག་གཉུག་མའི་དེ་ཉིད་གསལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8FC0:
      image_group_id: I1KG12637
      title: ''
      total_pages: 446
      order: 1
      base_file: 8FC0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
